export const projects = [
    {
        lecturer_id: "D2345",
        student_leader_id: "2501959296",
        title: "Fareebook",
        semester_id: "be992b30-4b38-4361-8404-25f2d6912754",
        course_id: "COMP6100001",
        class: "BW11",
        github_link: "https://github.com/darrzx/FaREbook",
        project_link: "https://github.com/darrzx/FaREbook",
        documentation: "https://www.orimi.com/pdf-test.pdf",
        thumbnail: "https://github.com/darrzx/FaREbook",
        description: "Fareebook is a comprehensive digital solution designed to simplify and streamline the booking process for travel services. It includes advanced features to manage bookings, provide real-time updates, and ensure seamless interactions between clients and providers.",
        status_id: 1,
        category_id: 2,
        major_id: 6,
        gallery: ["https://cdn0-production-images-kly.akamaized.net/UYY-Gy7HFn1rTTO2r5XVcR6nGa0=/640x360/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/4982180/original/042673500_1730095950-cara-menggambar-pemandangan.jpg"],
        group_members: ["2501970166", "2540115465"],
        technology_ids: [1, 5, 11],
        group: 1
    },
    {
        lecturer_id: "D6789",
        student_leader_id: "2540115465",
        title: "E-commerce App",
        semester_id: "be992b30-4b38-4361-8404-25f2d6912754",
        course_id: "COMP6100001",
        class: "BW11",
        github_link: "https://github.com/username/EcommerceApp",
        project_link: "https://ecommerceapp.com",
        documentation: "https://www.orimi.com/pdf-test.pdf",
        thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0P_sWONBhiAVR3_KbxWm95mEI64uBRs2kmiAhS9GqBvCPFf70Y7v6rVGgbDY9_xMTqrU&usqp=CAU",
        description: "The E-commerce App project provides a cutting-edge platform for buying and selling goods. With a highly scalable architecture, the app offers users a secure and intuitive shopping experience complete with payment integration, tracking, and personalized recommendations.",
        status_id: 1,
        category_id: 3,
        major_id: 6,
        gallery: [
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmODe2PNlQP5xHDfcizbsFY1poB64bBOVZyFH58xSrc0I8llRqjbUjOUkQHqsRxkg-b9o&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmODe2PNlQP5xHDfcizbsFY1poB64bBOVZyFH58xSrc0I8llRqjbUjOUkQHqsRxkg-b9o&usqp=CAU"
        ],
        group_members: ["2501959296", "2501970166"],
        technology_ids: [3, 7, 8],
        group: 2
    },
    {
        lecturer_id: "D5432",
        student_leader_id: "2501970166",
        title: "AI Chatbot",
        semester_id: "be992b30-4b38-4361-8404-25f2d6912754",
        course_id: "COMP6100001",
        class: "BW11",
        github_link: "https://github.com/username/AIChatbot",
        project_link: "https://aichatbot.com",
        documentation: "https://www.orimi.com/pdf-test.pdf",
        thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQq41ICT8h5P10y4_TtotzGgHMa40_oUOawgeQ0aQDIiTUjAoLqjivq_emLhWG1tcP7pwM&usqp=CAU",
        description: "The AI Chatbot project leverages machine learning and natural language processing to offer customer support solutions. This innovative platform is capable of understanding user queries and providing human-like responses, which help in automating routine interactions effectively.",
        status_id: 1,
        category_id: 1,
        major_id: 6,
        gallery: [
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0P_sWONBhiAVR3_KbxWm95mEI64uBRs2kmiAhS9GqBvCPFf70Y7v6rVGgbDY9_xMTqrU&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQq41ICT8h5P10y4_TtotzGgHMa40_oUOawgeQ0aQDIiTUjAoLqjivq_emLhWG1tcP7pwM&usqp=CAU"
        ],
        group_members: ["2501959296", "2540115465"],
        technology_ids: [2, 4, 9],
        group: 3
    },
    {
        lecturer_id: "D2345",
        student_leader_id: "2501959296",
        title: "Fareebook",
        semester_id: "be992b30-4b38-4361-8404-25f2d6912754",
        course_id: "COMP6100001",
        class: "BW22",
        github_link: "https://github.com/darrzx/FaREbook",
        project_link: "https://github.com/darrzx/FaREbook",
        documentation: "https://www.orimi.com/pdf-test.pdf",
        thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwYg9071jnR4RXsdsfc28hvNAEec7qFRfxYNIyI_mc2L-5Do_YeOD0dOSs7Mr437ah8U8&usqp=CAU",
        description: "Fareebook is a comprehensive digital solution designed to simplify and streamline the booking process for travel services. It includes advanced features to manage bookings, provide real-time updates, and ensure seamless interactions between clients and providers.",
        status_id: 2,
        category_id: 2,
        major_id: 6,
        gallery: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwYg9071jnR4RXsdsfc28hvNAEec7qFRfxYNIyI_mc2L-5Do_YeOD0dOSs7Mr437ah8U8&usqp=CAU"],
        group_members: ["2501970166", "2540115465"],
        technology_ids: [1, 5, 11],
        group: 1
    },
    {
        lecturer_id: "D6789",
        student_leader_id: "2540115465",
        title: "E-commerce App",
        semester_id: "be992b30-4b38-4361-8404-25f2d6912754",
        course_id: "COMP6100001",
        class: "BW22",
        github_link: "https://github.com/username/EcommerceApp",
        project_link: "https://ecommerceapp.com",
        documentation: "https://www.orimi.com/pdf-test.pdf",
        thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxCHpiew8ZyGiPY4t-RCMXQoYYLPlcde2x5Q6aO0oD3FOm2Xbx_uSipV8am8ba_y5nZgA&usqp=CAU",
        description: "The E-commerce App project provides a cutting-edge platform for buying and selling goods. With a highly scalable architecture, the app offers users a secure and intuitive shopping experience complete with payment integration, tracking, and personalized recommendations.",
        status_id: 2,
        category_id: 3,
        major_id: 6,
        gallery: [
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwYg9071jnR4RXsdsfc28hvNAEec7qFRfxYNIyI_mc2L-5Do_YeOD0dOSs7Mr437ah8U8&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwYg9071jnR4RXsdsfc28hvNAEec7qFRfxYNIyI_mc2L-5Do_YeOD0dOSs7Mr437ah8U8&usqp=CAU"
        ],
        group_members: ["2501959296", "2501970166"],
        technology_ids: [3, 7, 8],
        group: 2
    },
    {
        lecturer_id: "D5432",
        student_leader_id: "2501970166",
        title: "AI Chatbot",
        semester_id: "be992b30-4b38-4361-8404-25f2d6912754",
        course_id: "COMP6100001",
        class: "BW22",
        github_link: "https://github.com/username/AIChatbot",
        project_link: "https://aichatbot.com",
        documentation: "https://www.orimi.com/pdf-test.pdf",
        thumbnail: "https://img.pikbest.com/photo/20240809/beautiful-landscape-painting-of-nature-forest-background-image_10711075.jpg!w700wp",
        description: "The AI Chatbot project leverages machine learning and natural language processing to offer customer support solutions. This innovative platform is capable of understanding user queries and providing human-like responses, which help in automating routine interactions effectively.",
        status_id: 2,
        category_id: 1,
        major_id: 6,
        gallery: [
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfAFxobPbadSj98wV_mi91UADyg9JjeCQ2nURphZj1QdlUquf6BYnFUZz-pULn7ANJY0o&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfAFxobPbadSj98wV_mi91UADyg9JjeCQ2nURphZj1QdlUquf6BYnFUZz-pULn7ANJY0o&usqp=CAU"
        ],
        group_members: ["2501959296", "2540115465"],
        technology_ids: [2, 4, 9],
        group: 3
    },
    {
        lecturer_id: "D5432",
        student_leader_id: "2501970166",
        title: "Project Reviewed",
        semester_id: "be992b30-4b38-4361-8404-25f2d6912754",
        course_id: "COMP6100001",
        class: "BW22",
        github_link: "https://github.com/username/AIChatbot",
        project_link: "https://aichatbot.com",
        documentation: "https://www.orimi.com/pdf-test.pdf",
        thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvlLR-i2gUh0OcUWktZFznScJAQhsDyAIDbKYESAhdF1ZUp9q6kyI-PxIOYu7KGTFQt7A&usqp=CAU",
        description: "The E-commerce App project provides a cutting-edge platform for buying and selling goods. With a highly scalable architecture, the app offers users a secure and intuitive shopping experience complete with payment integration, tracking, and personalized recommendations.",
        status_id: 3,
        category_id: 1,
        major_id: 6,
        gallery: [
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5CZDNgQQyn-rYaDS7wV8x3o_GzvJA1-o_pgmYCAaZD9JdcIugpU0ZXviTFuvkZVZEVWg&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5CZDNgQQyn-rYaDS7wV8x3o_GzvJA1-o_pgmYCAaZD9JdcIugpU0ZXviTFuvkZVZEVWg&usqp=CAU"
        ],
        group_members: ["2504829348", "2504938237"],
        technology_ids: [2, 4, 9],
        group: 4
    },
    {
        lecturer_id: "D5432",
        student_leader_id: "2501959296",
        title: "Project Outstanding",
        semester_id: "be992b30-4b38-4361-8404-25f2d6912754",
        course_id: "COMP6100001",
        class: "BW22",
        github_link: "https://github.com/username/AIChatbot",
        project_link: "https://aichatbot.com",
        documentation: "https://www.orimi.com/pdf-test.pdf",
        thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7_FpfAiKvEx6eQ0UFl74t_NqcAvVoII8CwnCtTz1verUcqYyiqNGJS8Yu9lFszR0xLSY&usqp=CAU",
        description: "Fareebook is a comprehensive digital solution designed to simplify and streamline the booking process for travel services. It includes advanced features to manage bookings, provide real-time updates, and ensure seamless interactions between clients and providers.",
        status_id: 4,
        category_id: 1,
        major_id: 6,
        gallery: [
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2dBGO39U8cmYRBmYqLjH2gh6cF2n5uC1SBjpAMRXAADH1W3RvLqUiMP1tcL_-TR3CtG8&usqp=CAU",
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2dBGO39U8cmYRBmYqLjH2gh6cF2n5uC1SBjpAMRXAADH1W3RvLqUiMP1tcL_-TR3CtG8&usqp=CAU"
        ],
        group_members: ["2594059382", "2504938217"],
        technology_ids: [2, 4, 9],
        group: 5
    }
];
