export const projects = [
    {
        lecturer_id: "D2345",
        student_leader_id: "2501959296",
        title: "Fareebook",
        semester_id: "be992b30-4b38-4361-8404-25f2d6912754",
        course_id: "COMP6051049",
        class: "BW11",
        github_link: "https://github.com/darrzx/FaREbook",
        project_link: "https://github.com/darrzx/FaREbook",
        documentation: "https://github.com/darrzx/FaREbook",
        thumbnail: "https://github.com/darrzx/FaREbook",
        description: "Halo ini description buat testing hehehehe",
        status_id: 1,
        category_id: 2,
        major_id: 6,
        gallery: ["https://github.com/darrzx/FaREbook"],
        group_members: ["2501970166", "2540115465"],
        technology_ids: [1, 5, 11],
        group: 1
    },
    {
        lecturer_id: "D6789",
        student_leader_id: "2540115465",
        title: "E-commerce App",
        semester_id: "be992b30-4b38-4361-8404-25f2d6912754",
        course_id: "COMP7030050",
        class: "BW11",
        github_link: "https://github.com/username/EcommerceApp",
        project_link: "https://ecommerceapp.com",
        documentation: "https://github.com/username/EcommerceApp/wiki",
        thumbnail: "https://ecommerceapp.com/images/thumbnail.png",
        description: "An e-commerce application for buying and selling goods.",
        status_id: 1,
        category_id: 3,
        major_id: 6,
        gallery: [
            "https://ecommerceapp.com/images/gallery1.png",
            "https://ecommerceapp.com/images/gallery2.png"
        ],
        group_members: ["2501959296", "2501970166"],
        technology_ids: [3, 7, 8],
        group: 2
    },
    {
        lecturer_id: "D5432",
        student_leader_id: "2501970166",
        title: "AI Chatbot",
        semester_id: "be992b30-4b38-4361-8404-25f2d6912754",
        course_id: "COMP8098765",
        class: "BW11",
        github_link: "https://github.com/username/AIChatbot",
        project_link: "https://aichatbot.com",
        documentation: "https://github.com/username/AIChatbot/wiki",
        thumbnail: "https://aichatbot.com/images/thumbnail.png",
        description: "An intelligent chatbot for customer service automation.",
        status_id: 1,
        category_id: 1,
        major_id: 6,
        gallery: [
            "https://aichatbot.com/images/gallery1.png",
            "https://aichatbot.com/images/gallery2.png"
        ],
        group_members: ["2501959296", "2540115465"],
        technology_ids: [2, 4, 9],
        group: 3
    },
    {
        lecturer_id: "D2345",
        student_leader_id: "2501959296",
        title: "Fareebook",
        semester_id: "be992b30-4b38-4361-8404-25f2d6912754",
        course_id: "COMP6051049",
        class: "BW22",
        github_link: "https://github.com/darrzx/FaREbook",
        project_link: "https://github.com/darrzx/FaREbook",
        documentation: "https://github.com/darrzx/FaREbook",
        thumbnail: "https://github.com/darrzx/FaREbook",
        description: "Halo ini description buat testing hehehehe",
        status_id: 2,
        category_id: 2,
        major_id: 6,
        gallery: ["https://github.com/darrzx/FaREbook"],
        group_members: ["2501970166", "2540115465"],
        technology_ids: [1, 5, 11],
        group: 1
    },
    {
        lecturer_id: "D6789",
        student_leader_id: "2540115465",
        title: "E-commerce App",
        semester_id: "be992b30-4b38-4361-8404-25f2d6912754",
        course_id: "COMP7030050",
        class: "BW22",
        github_link: "https://github.com/username/EcommerceApp",
        project_link: "https://ecommerceapp.com",
        documentation: "https://github.com/username/EcommerceApp/wiki",
        thumbnail: "https://ecommerceapp.com/images/thumbnail.png",
        description: "An e-commerce application for buying and selling goods.",
        status_id: 2,
        category_id: 3,
        major_id: 6,
        gallery: [
            "https://ecommerceapp.com/images/gallery1.png",
            "https://ecommerceapp.com/images/gallery2.png"
        ],
        group_members: ["2501959296", "2501970166"],
        technology_ids: [3, 7, 8],
        group: 2
    },
    {
        lecturer_id: "D5432",
        student_leader_id: "2501970166",
        title: "AI Chatbot",
        semester_id: "be992b30-4b38-4361-8404-25f2d6912754",
        course_id: "COMP8098765",
        class: "BW22",
        github_link: "https://github.com/username/AIChatbot",
        project_link: "https://aichatbot.com",
        documentation: "https://github.com/username/AIChatbot/wiki",
        thumbnail: "https://aichatbot.com/images/thumbnail.png",
        description: "An intelligent chatbot for customer service automation.",
        status_id: 2,
        category_id: 1,
        major_id: 6,
        gallery: [
            "https://aichatbot.com/images/gallery1.png",
            "https://aichatbot.com/images/gallery2.png"
        ],
        group_members: ["2501959296", "2540115465"],
        technology_ids: [2, 4, 9],
        group: 3
    }
];
